tasks:
  - name: player-service-app
  - init: |
      python3 -m venv venv
      source venv/bin/activate
      pip install -r frf/requirements.txt
    command: |
      source venv/bin/activate

ports:
  - port: 5000
    onOpen: open-preview